//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OliWeb.Sites {
    
    
    public partial class StammAnglerSite {
        
        /// <summary>
        /// StammKoerper1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OliWeb.Controls.Koerper.StammKoerper StammKoerper1;
        
        /// <summary>
        /// StammAnglerGrid1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OliWeb.Controls.Koerper.ViewGrids.StammAnglerGrid StammAnglerGrid1;
        
        /// <summary>
        /// HilfePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel HilfePanel;
    }
}

