//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OliWeb {
    
    
    public partial class _default_old {
        
        /// <summary>
        /// _default control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm _default;
        
        /// <summary>
        /// Kopf1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OliWeb.Controls.Koerper.Kopf Kopf1;
        
        /// <summary>
        /// AnonymMenu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OliWeb.Controls.Floor.AnonymMenu AnonymMenu1;
        
        /// <summary>
        /// AnonymIntro1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OliWeb.Controls.Floor.AnonymIntro AnonymIntro1;
    }
}
