//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OliWeb.Controls.Koerper {
    
    
    public partial class Kopf {
        
        /// <summary>
        /// EinAusLoggen1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OliWeb.Controls.Floor.EinAusLoggen EinAusLoggen1;
        
        /// <summary>
        /// LogoControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OliWeb.Controls.Floor.LogoControl LogoControl1;
        
        /// <summary>
        /// LanguageSelect1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OliWeb.Controls.Gimicks.LanguageSelect LanguageSelect1;
        
        /// <summary>
        /// NachrichtLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label NachrichtLabel;
        
        /// <summary>
        /// CommandBar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OliWeb.Controls.Command.CommandBar CommandBar1;
    }
}

